//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HighScoreApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public int Number { get; set; }
        public int Scratch { get; set; }
        public int Spares { get; set; }
        public int Strikes { get; set; }
        public int PlayPosition { get; set; }
        public int HDCP { get; set; }
        public int TeamHDCP { get; set; }
        public string PlayerType { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public int BowlerId { get; set; }
        public int TeamId { get; set; }
        public int WeekNumber { get; set; }
        public int Lane { get; set; }
        public int League_Id { get; set; }
    
        public virtual Bowler Bowler { get; set; }
        public virtual League League { get; set; }
        public virtual Team Team { get; set; }
    }
}
